# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Test dependencies - no semantic versioning impact (processed first)
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test"  # No version bump - test dependencies only
    open-pull-requests-limit: 10
    groups:
      testing-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.junit.platform:*"
          - "com.approvaltests:*"
          - "org.hamcrest:*"
          - "io.mockk:*"
          - "ch.qos.logback:*"

  # Production dependencies - triggers semantic versioning (fallback for everything else)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 10
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"

      jackson-dependencies:
        patterns:
          - "com.fasterxml.jackson.*:*"

      json-xml-dependencies:
        patterns:
          - "com.google.code.gson:*"
          - "org.dom4j:*"

      utility-dependencies:
        patterns:
          - "org.apache.commons:*"
          - "org.slf4j:*"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact
